/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mobileworld.form;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import mobileworld.entity.PhieuGiamGia;
import mobileworld.main.SessionStorage;
import mobileworld.service.PhieuGiamGiaService.PhieuGiamGiaService;

/**
 *
 * @author Admin
 */
public class ViewInputPhieuGiamGia extends javax.swing.JPanel {

    private ViewGiamGia1 jpanelHien;

    /**
     * Creates new form ViewInputPhieuGiamGia
     */
    public ViewInputPhieuGiamGia() {
        initComponents();
    }

    DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    SimpleDateFormat spxHien = new SimpleDateFormat("dd-MM-yyyy");
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<PhieuGiamGia> ds = new ArrayList<>();
    private List<PhieuGiamGia> ds2 = new ArrayList<>();
    private List<PhieuGiamGia> dsPhu = new ArrayList<>();
    private PhieuGiamGiaService sr = new PhieuGiamGiaService();
    DecimalFormat decimalFormat = new DecimalFormat("###,###");
    private DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSoLan = new mobileworld.swing.TextField();
        txtPhanTramGiam = new mobileworld.swing.TextField();
        txtTen = new mobileworld.swing.TextField();
        txtHoaDonToiThieu = new mobileworld.swing.TextField();
        txtSoTienGiamToiDa = new mobileworld.swing.TextField();
        jLabel4 = new javax.swing.JLabel();
        cboNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        cboNgayKT = new com.toedter.calendar.JDateChooser();
        btnAdd = new mobileworld.swing.ButtonCustom();
        btnBack = new mobileworld.swing.ButtonCustom();
        btnLogo = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Phiếu Giảm Giá");

        txtSoLan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoLan.setLabelText("Số Lượng Được Phép Sử Dụng");

        txtPhanTramGiam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhanTramGiam.setLabelText("Phần Trăm Giảm");

        txtTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTen.setLabelText("Tên Khuyến Mãi");

        txtHoaDonToiThieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHoaDonToiThieu.setLabelText("Hóa Đơn Tối Thiểu");
        txtHoaDonToiThieu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoaDonToiThieuKeyTyped(evt);
            }
        });

        txtSoTienGiamToiDa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoTienGiamToiDa.setLabelText("Số Tiền Giảm Tối Đa");
        txtSoTienGiamToiDa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoTienGiamToiDaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Ngày Bắt Đầu");

        cboNgayBatDau.setDateFormatString("dd-MM-yyyy");
        cboNgayBatDau.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Ngày Sử Dụng Cuối");

        cboNgayKT.setDateFormatString("dd-MM-yyyy");
        cboNgayKT.setOpaque(false);

        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileworld/icon/icons8-add-24.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileworld/icon/icons8-back-24.png"))); // NOI18N
        btnBack.setAlignmentX(0.5F);
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLogo.setForeground(new java.awt.Color(255, 255, 255));
        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileworld/icon/Logomb.png"))); // NOI18N
        btnLogo.setBorder(null);
        btnLogo.setBorderPainted(false);
        btnLogo.setContentAreaFilled(false);
        btnLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtHoaDonToiThieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 592, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboNgayBatDau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoTienGiamToiDa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboNgayKT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoLan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addComponent(btnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSoLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoaDonToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoTienGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(btnLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public PhieuGiamGia getFormData() {
        String ten = txtTen.getText().trim();
        int soLan = Integer.valueOf(Integer.parseInt(txtSoLan.getText().trim().replace(",", "")));
        float phanTram = Float.valueOf(Float.parseFloat(txtPhanTramGiam.getText().trim().replace("%", "")));
        String hoaDonFormat = txtHoaDonToiThieu.getText().replace(",", "");
        String soTienFormat = txtSoTienGiamToiDa.getText().replace(",", "");
        float hoaDonMin = Float.valueOf(Float.parseFloat(hoaDonFormat));
        float soTiemGiamMax = Float.valueOf(Float.parseFloat(soTienFormat));
        String maNV = SessionStorage.getInstance().getUsername();
        int tt = 1;

        //Bien thoi gian
        Date getNgayBD = cboNgayBatDau.getDate();
        LocalDateTime ngayBD = getNgayBD.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        LocalDate ngayBDLocalDate = ngayBD.toLocalDate();
        Date getNgayKT = cboNgayKT.getDate();
        LocalDateTime ngayKT = getNgayKT.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        LocalDate ngayKTLocalDate = ngayKT.toLocalDate();
        LocalDateTime ngayThucTe = LocalDateTime.now();
        LocalDate ngayTTLC = ngayThucTe.toLocalDate();

        if (ngayBDLocalDate.equals(ngayTTLC) && ngayKTLocalDate.isAfter(ngayTTLC)) {
            tt = 1;
        } else if (ngayBDLocalDate.isAfter(ngayTTLC) && ngayKTLocalDate.isAfter(ngayTTLC)) {
            tt = 2;
        }

        PhieuGiamGia pgg = new PhieuGiamGia(ten, soLan, phanTram, soTiemGiamMax, hoaDonMin, ngayBD, ngayKT, tt, ten, 1, ngayThucTe, maNV, ngayThucTe, maNV);       
        return pgg;
    }


    private void txtHoaDonToiThieuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoaDonToiThieuKeyTyped
        // TODO add your handling code here:
        if (!txtHoaDonToiThieu.getText().trim().isEmpty()) {
            String text = txtHoaDonToiThieu.getText();
            text = text.replaceAll("[^\\d]", "");

            if (!text.isEmpty()) {
                try {
                    long number = Long.parseLong(text);
                    DecimalFormat decimalFormat = new DecimalFormat("#,##0");
                    txtHoaDonToiThieu.setText(decimalFormat.format(number));
                } catch (NumberFormatException ex) {
                    ex.printStackTrace();
                }
            }
        }

    }//GEN-LAST:event_txtHoaDonToiThieuKeyTyped

    private void txtSoTienGiamToiDaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTienGiamToiDaKeyTyped
        // TODO add your handling code here:
        if (!txtSoTienGiamToiDa.getText().trim().isBlank()) {
            Document document = txtSoTienGiamToiDa.getDocument();
            try {
                String text = document.getText(0, document.getLength());
                text = text.replaceAll("[^\\d]", "");
                long number = Long.parseLong(text);

                DecimalFormat decimalFormat = new DecimalFormat("#,##0");
                String formattedNumber = decimalFormat.format(number);
                txtSoTienGiamToiDa.setText(formattedNumber);

            } catch (BadLocationException | NumberFormatException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtSoTienGiamToiDaKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String hoaDonFormat = txtHoaDonToiThieu.getText().replace(",", "");
        String soTienFormat = txtSoTienGiamToiDa.getText().replace(",", "");
        String soLanFormat = txtSoLan.getText().replace(",", "");
        String phanTramFormat = txtPhanTramGiam.getText().replace("%", "");
        if (txtTen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui long nhap ten khuyen mai");
            return;
        }

        if (txtSoLan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lần được phép sử dụng");
            return;
        }

        if (txtHoaDonToiThieu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập hóa đơn tối thiếu");
            return;
        }
        if (!hoaDonFormat.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lại hóa đơn tối thiếu");
            return;
        }
        if (txtPhanTramGiam.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập phần trăm giảm");
            return;
        }
        if (!phanTramFormat.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lại phần trăm giảm");
            return;
        }
        if (txtSoTienGiamToiDa.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền giảm tối đa");
            return;
        }
        if (!soTienFormat.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lại số tiền giảm tối đa");
            return;
        }

        Date getNgayBD = cboNgayBatDau.getDate();
        Date getNgayKT = cboNgayKT.getDate();

        if (getNgayBD == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày bắt đầu");
            return;
        }

        if (getNgayKT == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày kết thúc");
            return;
        }

        LocalDateTime ngayBD = getNgayBD.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        LocalDate ngayBDLocalDate = ngayBD.toLocalDate();
        LocalDateTime ngayKT = getNgayKT.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        LocalDate ngayKTLocalDate = ngayKT.toLocalDate();
        LocalDateTime ngayThucTe = LocalDateTime.now();
        LocalDate ngayTTLC = ngayThucTe.toLocalDate();

        if (ngayBDLocalDate.isBefore(ngayTTLC)) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lại ngày bắt đầu");
            return;
        }


        if (ngayKTLocalDate.isBefore(ngayBDLocalDate)) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lại ngày kết thúc");
            return;
        }

//        if (ngayBDLocalDate.isEqual(ngayTTLC) && ngayKTLocalDate.isEqual(ngayBDLocalDate) || ngayBDLocalDate.isAfter(ngayTTLC) && ngayKTLocalDate.isEqual(ngayBDLocalDate)) {
//            JOptionPane.showMessageDialog(this, "Ngay bat dau va ket thuc khong duoc la cung 1 ngay");
//            return;
//        }



        int lc = JOptionPane.showConfirmDialog(this, "Bạn có muốn Add dữ liệu không?", "Notification", JOptionPane.YES_NO_OPTION);
        if (lc == JOptionPane.YES_OPTION) {
            sr.addData(getFormData());

            JOptionPane.showMessageDialog(this, "Đã Add dữ liệu");

            int lc2 = JOptionPane.showConfirmDialog(this, "Bạn có muốn quay về trang phiếu giảm giá chính không?", "Notification", JOptionPane.YES_NO_OPTION);
            if (lc2 == JOptionPane.YES_OPTION) {
                jpanelHien = new ViewGiamGia1();
                jPanel1.setVisible(false);
                jLabel1.setVisible(false);
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                frame.getContentPane().remove(this);
                javax.swing.GroupLayout layout = (javax.swing.GroupLayout) this.getLayout();
                layout.replace(jPanel1, jpanelHien);
                jpanelHien.setBounds(jPanel1.getBounds());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Bạn đã chọn NO");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jpanelHien = new ViewGiamGia1();
        jPanel1.setVisible(false);
        jLabel1.setVisible(false);
        btnBack.setVisible(false);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().remove(this);
        javax.swing.GroupLayout layout = (javax.swing.GroupLayout) this.getLayout();
        layout.replace(jPanel1, jpanelHien);
        jpanelHien.setBounds(jPanel1.getBounds());
    }//GEN-LAST:event_btnBackActionPerformed

//    private void askIdentityQuestion() {
//        int response = JOptionPane.showConfirmDialog(null, "Do you want to know who I am?", "Question", JOptionPane.YES_NO_OPTION);
//        if (response == JOptionPane.YES_OPTION) {
//            response = JOptionPane.showConfirmDialog(null, "Are you sure?", "Question", JOptionPane.YES_NO_OPTION);
//            if (response == JOptionPane.YES_OPTION) {
//                JOptionPane.showMessageDialog(null, "Hello, I'm Mobile World");
//            }
//            if (response == JOptionPane.NO_OPTION) {
//                JOptionPane.showMessageDialog(null, "Glad you don't want to know, I will have to take you down you if you know my Identity");
//            }
//        } else {
//            response = JOptionPane.showConfirmDialog(null, "Are you sure? you might want to hear the answer", "Question", JOptionPane.YES_NO_OPTION);
//            if (response == JOptionPane.YES_OPTION) {
//                JOptionPane.showMessageDialog(null, "Glad you don't want to know, I will have to take you down you if you know my Identity");
//            }
//            if (response == JOptionPane.NO_OPTION) {
//                JOptionPane.showMessageDialog(null, "Let's do this again");
//                askIdentityQuestion();
//            }
//        }
//    }

    private void btnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoActionPerformed
        // TODO add your handling code here:
//        askIdentityQuestion();
    }//GEN-LAST:event_btnLogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mobileworld.swing.ButtonCustom btnAdd;
    private mobileworld.swing.ButtonCustom btnBack;
    private javax.swing.JButton btnLogo;
    private com.toedter.calendar.JDateChooser cboNgayBatDau;
    private com.toedter.calendar.JDateChooser cboNgayKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private mobileworld.swing.TextField txtHoaDonToiThieu;
    private mobileworld.swing.TextField txtPhanTramGiam;
    private mobileworld.swing.TextField txtSoLan;
    private mobileworld.swing.TextField txtSoTienGiamToiDa;
    private mobileworld.swing.TextField txtTen;
    // End of variables declaration//GEN-END:variables
}
